package udel.GardenProject.enums;

import javafx.scene.paint.Color;

/**
 * This is one of the stupidest things I've ever done in Java. There is no 
 * built-in enum for Color. Java has a Color class which has zero helper methods
 * for:
 * <ol>
 * <li>Getting all the colors, unlike an enum's <code>values()</code>.</li>
 * <li>Converting those colors to helpful strings for checkbox lists, and</li>
 * <li>Convert strings of color names back into a Color object/enum.</li>
 * </ol>
 * 
 * Color has a <code>web()</code> method that converts a CSS color into a Color
 * object, but it's bad. CSS can specify a color such as 
 * <code>color: red;</code>, but JavaFX's Color class can't handle that complex
 * problem, apparently. Even if it did work (like it's supposed to), it doesn't
 * acheive the other two requirements we have above.<br><br>
 * 
 * May hardship rain upon Oracle for making me do this.
 * 
 * @author Team 0
 */
public enum Colors {
	
	ALICEBLUE(Color.ALICEBLUE),
	ANTIQUEWHITE(Color.ANTIQUEWHITE),
	AQUA(Color.AQUA),
	AQUAMARINE(Color.AQUAMARINE),
	AZURE(Color.AZURE),
	BEIGE(Color.BEIGE),
	BISQUE(Color.BISQUE),
	BLACK(Color.BLACK),
	BLANCHEDALMOND(Color.BLANCHEDALMOND),
	BLUE(Color.BLUE),
	BLUEVIOLET(Color.BLUEVIOLET),
	BROWN(Color.BROWN),
	BURLYWOOD(Color.BURLYWOOD),
	CADETBLUE(Color.CADETBLUE),
	CHARTREUSE(Color.CHARTREUSE),
	CHOCOLATE(Color.CHOCOLATE),
	CORAL(Color.CORAL),
	CORNFLOWERBLUE(Color.CORNFLOWERBLUE),
	CORNSILK(Color.CORNSILK),
	CRIMSON(Color.CRIMSON),
	CYAN(Color.CYAN),
	DARKBLUE(Color.DARKBLUE),
	DARKCYAN(Color.DARKCYAN),
	DARKGOLDENROD(Color.DARKGOLDENROD),
	DARKGRAY(Color.DARKGRAY),
	DARKGREEN(Color.DARKGREEN),
	DARKGREY(Color.DARKGREY),
	DARKKHAKI(Color.DARKKHAKI),
	DARKMAGENTA(Color.DARKMAGENTA),
	DARKOLIVEGREEN(Color.DARKOLIVEGREEN),
	DARKORANGE(Color.DARKORANGE),
	DARKORCHID(Color.DARKORCHID),
	DARKRED(Color.DARKRED),
	DARKSALMON(Color.DARKSALMON),
	DARKSEAGREEN(Color.DARKSEAGREEN),
	DARKSLATEBLUE(Color.DARKSLATEBLUE),
	DARKSLATEGRAY(Color.DARKSLATEGRAY),
	DARKSLATEGREY(Color.DARKSLATEGREY),
	DARKTURQUOISE(Color.DARKTURQUOISE),
	DARKVIOLET(Color.DARKVIOLET),
	DEEPPINK(Color.DEEPPINK),
	DEEPSKYBLUE(Color.DEEPSKYBLUE),
	DIMGRAY(Color.DIMGRAY),
	DIMGREY(Color.DIMGREY),
	DODGERBLUE(Color.DODGERBLUE),
	FIREBRICK(Color.FIREBRICK),
	FLORALWHITE(Color.FLORALWHITE),
	FORESTGREEN(Color.FORESTGREEN),
	FUCHSIA(Color.FUCHSIA),
	GAINSBORO(Color.GAINSBORO),
	GHOSTWHITE(Color.GHOSTWHITE),
	GOLD(Color.GOLD),
	GOLDENROD(Color.GOLDENROD),
	GRAY(Color.GRAY),
	GREEN(Color.GREEN),
	GREENYELLOW(Color.GREENYELLOW),
	GREY(Color.GREY),
	HONEYDEW(Color.HONEYDEW),
	HOTPINK(Color.HOTPINK),
	INDIANRED(Color.INDIANRED),
	INDIGO(Color.INDIGO),
	IVORY(Color.IVORY),
	KHAKI(Color.KHAKI),
	LAVENDER(Color.LAVENDER),
	LAVENDERBLUSH(Color.LAVENDERBLUSH),
	LAWNGREEN(Color.LAWNGREEN),
	LEMONCHIFFON(Color.LEMONCHIFFON),
	LIGHTBLUE(Color.LIGHTBLUE),
	LIGHTCORAL(Color.LIGHTCORAL),
	LIGHTCYAN(Color.LIGHTCYAN),
	LIGHTGOLDENRODYELLOW(Color.LIGHTGOLDENRODYELLOW),
	LIGHTGRAY(Color.LIGHTGRAY),
	LIGHTGREEN(Color.LIGHTGREEN),
	LIGHTGREY(Color.LIGHTGREY),
	LIGHTPINK(Color.LIGHTPINK),
	LIGHTSALMON(Color.LIGHTSALMON),
	LIGHTSEAGREEN(Color.LIGHTSEAGREEN),
	LIGHTSKYBLUE(Color.LIGHTSKYBLUE),
	LIGHTSLATEGRAY(Color.LIGHTSLATEGRAY),
	LIGHTSLATEGREY(Color.LIGHTSLATEGREY),
	LIGHTSTEELBLUE(Color.LIGHTSTEELBLUE),
	LIGHTYELLOW(Color.LIGHTYELLOW),
	LIME(Color.LIME),
	LIMEGREEN(Color.LIMEGREEN),
	LINEN(Color.LINEN),
	MAGENTA(Color.MAGENTA),
	MAROON(Color.MAROON),
	MEDIUMAQUAMARINE(Color.MEDIUMAQUAMARINE),
	MEDIUMBLUE(Color.MEDIUMBLUE),
	MEDIUMORCHID(Color.MEDIUMORCHID),
	MEDIUMPURPLE(Color.MEDIUMPURPLE),
	MEDIUMSEAGREEN(Color.MEDIUMSEAGREEN),
	MEDIUMSLATEBLUE(Color.MEDIUMSLATEBLUE),
	MEDIUMSPRINGGREEN(Color.MEDIUMSPRINGGREEN),
	MEDIUMTURQUOISE(Color.MEDIUMTURQUOISE),
	MEDIUMVIOLETRED(Color.MEDIUMVIOLETRED),
	MIDNIGHTBLUE(Color.MIDNIGHTBLUE),
	MINTCREAM(Color.MINTCREAM),
	MISTYROSE(Color.MISTYROSE),
	MOCCASIN(Color.MOCCASIN),
	NAVAJOWHITE(Color.NAVAJOWHITE),
	NAVY(Color.NAVY),
	OLDLACE(Color.OLDLACE),
	OLIVE(Color.OLIVE),
	OLIVEDRAB(Color.OLIVEDRAB),
	ORANGE(Color.ORANGE),
	ORANGERED(Color.ORANGERED),
	ORCHID(Color.ORCHID),
	PALEGOLDENROD(Color.PALEGOLDENROD),
	PALEGREEN(Color.PALEGREEN),
	PALETURQUOISE(Color.PALETURQUOISE),
	PALEVIOLETRED(Color.PALEVIOLETRED),
	PAPAYAWHIP(Color.PAPAYAWHIP),
	PEACHPUFF(Color.PEACHPUFF),
	PERU(Color.PERU),
	PINK(Color.PINK),
	PLUM(Color.PLUM),
	POWDERBLUE(Color.POWDERBLUE),
	PURPLE(Color.PURPLE),
	RED(Color.RED),
	ROSYBROWN(Color.ROSYBROWN),
	ROYALBLUE(Color.ROYALBLUE),
	SADDLEBROWN(Color.SADDLEBROWN),
	SALMON(Color.SALMON),
	SANDYBROWN(Color.SANDYBROWN),
	SEAGREEN(Color.SEAGREEN),
	SEASHELL(Color.SEASHELL),
	SIENNA(Color.SIENNA),
	SILVER(Color.SILVER),
	SKYBLUE(Color.SKYBLUE),
	SLATEBLUE(Color.SLATEBLUE),
	SLATEGRAY(Color.SLATEGRAY),
	SLATEGREY(Color.SLATEGREY),
	SNOW(Color.SNOW),
	SPRINGGREEN(Color.SPRINGGREEN),
	STEELBLUE(Color.STEELBLUE),
	TAN(Color.TAN),
	TEAL(Color.TEAL),
	THISTLE(Color.THISTLE),
	TOMATO(Color.TOMATO),
	TRANSPARENT(Color.TRANSPARENT),
	TURQUOISE(Color.TURQUOISE),
	VIOLET(Color.VIOLET),
	WHEAT(Color.WHEAT),
	WHITE(Color.WHITE),
	WHITESMOKE(Color.WHITESMOKE),
	YELLOW(Color.YELLOW),
	YELLOWGREEN(Color.YELLOWGREEN);
	
	private Color c;
	
	private Colors(Color c) {
		this.c = c;
	}
	
	public Color getColor() {
		return this.c;
	}

}